development:
  type: pop
  server: mail.rendale.com
  username: m2998439
  password: tr1vial
  
test:
  type: pop
  server: mail.rendale.com
  username: m2998439
  password: tr1vial
  
production:
  type: pop
  server: mail.rendale.com
  username: m2998439
  password: tr1vial
